[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  set laststatus=2
	let g:airline_powerline_fonts = 1
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#tabline#buffer_idx_mode = 1
	let g:airline#extensions#whitespace#mixed_indent_algo = 1
	let g:airline_theme = 'bubblegum'
	nmap <C-p> <Plug>AirlineSelectPrevTab
	nmap <C-n> <Plug>AirlineSelectNextTab
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
	set bg=dark
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.5'

